const list = [
    "advlist",
    "anchor",
    "autolink",
    // "autosave",
    "code",
    "codesample",
    "colorpicker",
    "colorpicker",
    "contextmenu",
    "directionality",
    "emoticons",
    "fullscreen",
    "hr",
    "image",
    // 图片在线修改之后，会改成BASE64存储
    "imagetools",
    "insertdatetime",
    "link",
    "lists",
    "media",
    "nonbreaking",
    "noneditable",
    "pagebreak",
    "paste",
    "preview",
    "print",
    "save",
    "searchreplace",
    "spellchecker",
    "tabfocus",
    "table",
    "template",
    "textcolor",
    "textpattern",
    "visualblocks",
    "visualchars",
    "wordcount",
]
export const plugins = [list.join(" ")];